# Generated by Django 3.0.10 on 2020-10-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='publish_Date',
            new_name='publish_date',
        ),
    ]
